services:
  - type: web
    name: moviecat-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: RENDER_DATABASE_URL
        fromDatabase:
          name: moviecat-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: moviecat-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: moviecat-db
          property: password
      - key: TMDB_API_KEY
        sync: false
  - type: web
    name: moviecat-frontend
    runtime: docker
    plan: free
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: BACKEND_URL
        fromService:
          name: moviecat-app
          type: web
          property: hostport

databases:
  - name: moviecat-db
    plan: free
    databaseName: moviecat_db
    postgresMajorVersion: "16"
